### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by stephens999** [stephenslab/rssr#2]
I get ERROR: dependency ‘h5’ is not available for package ‘rssr’
devtools::install_github("stephenslab/rssr",ref="v0.1.0-alpha")

Downloading GitHub repo stephenslab/rssr@v0.1.0-alpha
from URL https://api.github.com/repos/stephenslab/rssr/zipball/v0.1.0-alpha
Installing rssr
trying URL 'https://cran.rstudio.com/bin/macosx/mavericks/contrib/3.3/future_1.3.0.tgz'
Content type 'application/x-gzip' length 267478 bytes (261 KB)
==================================================
downloaded 261 KB

Installing future
trying URL 'https://cran.rstudio.com/bin/macosx/mavericks/contrib/3.3/globals_0.8.0.tgz'
Content type 'application/x-gzip' length 45161 bytes (44 KB)
==================================================
downloaded 44 KB

Installing globals
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  '/private/var/folders/1f/d96lz9ts15g81dqs_hcc_9cr0000gq/T/RtmpPSRiIa/devtoolsa3056ffff534/globals'  \
  --library='/Users/stephens/Dropbox/Rpackages' --install-tests 

* installing *binary* package ‘globals’ ...
* DONE (globals)
trying URL 'https://cran.rstudio.com/bin/macosx/mavericks/contrib/3.3/listenv_0.6.0.tgz'
Content type 'application/x-gzip' length 49509 bytes (48 KB)
==================================================
downloaded 48 KB

Installing listenv
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  '/private/var/folders/1f/d96lz9ts15g81dqs_hcc_9cr0000gq/T/RtmpPSRiIa/devtoolsa305582782a/listenv'  \
  --library='/Users/stephens/Dropbox/Rpackages' --install-tests 

* installing *binary* package ‘listenv’ ...
* DONE (listenv)
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  '/private/var/folders/1f/d96lz9ts15g81dqs_hcc_9cr0000gq/T/RtmpPSRiIa/devtoolsa3051e5b182f/future'  \
  --library='/Users/stephens/Dropbox/Rpackages' --install-tests 

* installing *binary* package ‘future’ ...
* DONE (future)
trying URL 'https://cran.rstudio.com/bin/macosx/mavericks/contrib/3.3/future.BatchJobs_0.13.1.tgz'
Content type 'application/x-gzip' length 92244 bytes (90 KB)
==================================================
downloaded 90 KB

Installing future.BatchJobs
trying URL 'https://cran.rstudio.com/bin/macosx/mavericks/contrib/3.3/BatchJobs_1.6.tgz'
Content type 'application/x-gzip' length 419995 bytes (410 KB)
==================================================
downloaded 410 KB

Installing BatchJobs
trying URL 'https://cran.rstudio.com/bin/macosx/mavericks/contrib/3.3/fail_1.3.tgz'
Content type 'application/x-gzip' length 39466 bytes (38 KB)
==================================================
downloaded 38 KB

Installing fail
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  '/private/var/folders/1f/d96lz9ts15g81dqs_hcc_9cr0000gq/T/RtmpPSRiIa/devtoolsa30514d14973/fail'  \
  --library='/Users/stephens/Dropbox/Rpackages' --install-tests 

* installing *binary* package ‘fail’ ...
* DONE (fail)
trying URL 'https://cran.rstudio.com/bin/macosx/mavericks/contrib/3.3/sendmailR_1.2-1.tgz'
Content type 'application/x-gzip' length 28159 bytes (27 KB)
==================================================
downloaded 27 KB

Installing sendmailR
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  '/private/var/folders/1f/d96lz9ts15g81dqs_hcc_9cr0000gq/T/RtmpPSRiIa/devtoolsa30573b05ce4/sendmailR'  \
  --library='/Users/stephens/Dropbox/Rpackages' --install-tests 

* installing *binary* package ‘sendmailR’ ...
* DONE (sendmailR)
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  '/private/var/folders/1f/d96lz9ts15g81dqs_hcc_9cr0000gq/T/RtmpPSRiIa/devtoolsa30552727aa1/BatchJobs'  \
  --library='/Users/stephens/Dropbox/Rpackages' --install-tests 

* installing *binary* package ‘BatchJobs’ ...
* DONE (BatchJobs)
trying URL 'https://cran.rstudio.com/bin/macosx/mavericks/contrib/3.3/R.utils_2.5.0.tgz'
Content type 'application/x-gzip' length 983152 bytes (960 KB)
==================================================
downloaded 960 KB

Installing R.utils
trying URL 'https://cran.rstudio.com/bin/macosx/mavericks/contrib/3.3/R.methodsS3_1.7.1.tgz'
Content type 'application/x-gzip' length 55551 bytes (54 KB)
==================================================
downloaded 54 KB

Installing R.methodsS3
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  '/private/var/folders/1f/d96lz9ts15g81dqs_hcc_9cr0000gq/T/RtmpPSRiIa/devtoolsa305478f8073/R.methodsS3'  \
  --library='/Users/stephens/Dropbox/Rpackages' --install-tests 

* installing *binary* package ‘R.methodsS3’ ...
* DONE (R.methodsS3)
trying URL 'https://cran.rstudio.com/bin/macosx/mavericks/contrib/3.3/R.oo_1.21.0.tgz'
Content type 'application/x-gzip' length 775447 bytes (757 KB)
==================================================
downloaded 757 KB

Installing R.oo
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  '/private/var/folders/1f/d96lz9ts15g81dqs_hcc_9cr0000gq/T/RtmpPSRiIa/devtoolsa3053b38759d/R.oo'  \
  --library='/Users/stephens/Dropbox/Rpackages' --install-tests 

* installing *binary* package ‘R.oo’ ...
* DONE (R.oo)
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  '/private/var/folders/1f/d96lz9ts15g81dqs_hcc_9cr0000gq/T/RtmpPSRiIa/devtoolsa3054d4e354d/R.utils'  \
  --library='/Users/stephens/Dropbox/Rpackages' --install-tests 

* installing *binary* package ‘R.utils’ ...
* DONE (R.utils)
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  '/private/var/folders/1f/d96lz9ts15g81dqs_hcc_9cr0000gq/T/RtmpPSRiIa/devtoolsa3057e83d5b1/future.BatchJobs'  \
  --library='/Users/stephens/Dropbox/Rpackages' --install-tests 

* installing *binary* package ‘future.BatchJobs’ ...
* DONE (future.BatchJobs)
trying URL 'https://cran.rstudio.com/bin/macosx/mavericks/contrib/3.3/RcppParallel_4.3.20.tgz'
Content type 'application/x-gzip' length 485784 bytes (474 KB)
==================================================
downloaded 474 KB

Installing RcppParallel
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  '/private/var/folders/1f/d96lz9ts15g81dqs_hcc_9cr0000gq/T/RtmpPSRiIa/devtoolsa30541db80fb/RcppParallel'  \
  --library='/Users/stephens/Dropbox/Rpackages' --install-tests 

* installing *binary* package ‘RcppParallel’ ...
* DONE (RcppParallel)
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  '/private/var/folders/1f/d96lz9ts15g81dqs_hcc_9cr0000gq/T/RtmpPSRiIa/devtoolsa305534a76a2/stephenslab-rssr-467571c'  \
  --library='/Users/stephens/Dropbox/Rpackages' --install-tests 

ERROR: dependency ‘h5’ is not available for package ‘rssr’
* removing ‘/Users/stephens/Dropbox/Rpackages/rssr’
Error: Command failed (1)

**Comment by xiangzhu** [comment]
@stephens999  do you have package `h5` installed?
https://cran.r-project.org/web/packages/h5/index.html

> ERROR: dependency ‘h5’ is not available for package ‘rssr’

**Comment by stephens999** [comment]
it works after i installed h5 (which required brew install homebrew/science/hdf5 --enable-cxx)

**Comment by stephens999** [comment]
should maybe give the user a heads up in the readme if this package needs manually installing

**Comment by CreRecombinase** [comment]
Package shouldn't require manual installation now that HDF5 is no longer a dependency #5
