### ISSUE TITLE
Make h5 package "suggests" instead of "depends"

### ISSUE THREAD

**Issue by pcarbo** [stephenslab/rssr#5]
We had a discussion about this on Slack, but I thought I'd post an issue about it since it is a better way to document these discussions.

The main bottleneck is the `h5` package, which is poorly documented, and difficult to install. In particular, I can see that this difficulty would prevent a lot of people (e.g., Windows users) from using the package.

The `h5` package is not technically necessary for the core functionality of `rssr`, so it is better practice to make it "suggested" rather than "depends". The CRAN manual gives good guidance on how to work with Suggested packages: see [here](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Suggested-packages).

Below, I've attached a version of the `rssr` package with the h5 stuff removed, and the h5 dependency removed. The `example.Rmd` vignette still works without this.

[rssr-0.1.1-alpha-noh5.tar.gz](https://github.com/stephenslab/rssr/files/818731/rssr-0.1.1-alpha-noh5.tar.gz)

**Comment by PeteHaitch** [comment]
Was browsing this project and just thought I'd drop this FYI (you may well have considered these, if so, apologies). 

You might have more luck with the [**rhdf5** Bioconductor package](https://bioconductor.org/packages/release/bioc/html/rhdf5.html) than the **h5** package. I'm fairly sure it 'just works' on Windows (I think by bundling everything you need on most systems in with the package). I know of at least a few packages that are successfully using this to read/write HDF5 files in R. One such package is the [**HDF5Array** Bioconductor package](http://bioconductor.org/packages/release/bioc/html/HDF5Array.html). This is a higher-level package that abstracts away the need to really access the HDF5 API, so it may not be suitable for what you're doing here, but I thought it worth mentioning.

**Comment by xiangzhu** [comment]
@PeteHaitch  Thank you very much for providing us with the information!

**Comment by CreRecombinase** [comment]
Closing this as HDF5 is no longer a dependency( #10 )
